[package]
name = "a---"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["metaspace <metaspacehost@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "ğŸ¦€ all ğŸ¦€ my ğŸ¦€ peeps ğŸ¦€ is ğŸ¦€ crabs ğŸ¦€"


[dependencies]
